# Use an official Node.js runtime as a parent image
FROM node:18.17.0

# Set the working directory in the container
WORKDIR /imageconverter

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install 


# Copy the rest of the application code to the working directory
COPY . .

# Command to run the application
CMD ["node", "imageconverter.js"]